# Generated by Django 3.2.20 on 2023-07-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_test',
            new_name='message_text',
        ),
    ]
