# Generated by Django 3.2.20 on 2023-07-28 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classmateapp', '0005_auto_20230728_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_members',
        ),
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
